from . import courses
from . import pages
from . import lesson
from . import task
from . import login
from . import made_cource
from . import made_lesson
from . import fix_lesson_theory
from . import fix_task